server:
  port: 9001
  servlet:
    context-path: /api

spring:
  profiles:
      active: dev
      logging:
        level:
          org.springframework.web: debug
  datasource:
    dynamic:
      primary: mysql
      datasource:
        mysql:
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://127.0.0.1:3306/myblog?serverTimezone=CTT&useSSL=false&useUnicode=true&characterEncoding=utf8
          username: root
          password: 123456
  # redis
  redis:
    host: 47.102.145.172
    port: 6379
    password: wadewei
  # 发送邮件相关配置
  mail:
      host: smtp.qq.com
      username: 745696658@qq.com
      password: hqygpmumqdsxbfhh
      default-encoding: utf-8
      properties:
        mail:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
  # rabbitmq 相关配置
  rabbitmq:
    host: 47.102.145.172
    port: 5672
    username: wadewei
    password: wadewei
    virtual-host: /myblog
    template:
      retry:
        enabled: true
        max-interval: 30000ms
        initial-interval: 10000ms
        multiplier: 2
  aop:
    proxy-target-class: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 30MB
      max-request-size: 20MB
    http:
      encoding:
        charset: UTF-8
        force: true
        enabled: true

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: wade.wei.entity

blog:
  jwt:
    secret: ly@Login(Auth}*^31)&yun6%f3q2 # 登录校验的密钥
    pubKeyPath: H:/bystander/id_rsa.pub # 公钥地址
    priKeyPath: H:/bystander/id_rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: BL_TOKEN
    cookieMaxAge: 1800